project:
  type: website
  output-dir: docs

website:
  title: "Santhoshi N Krishnan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research overview.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

  
# ~ additional metadata excluded for brevity ~

editor: visual

