---
title: "Publications and Presentations"
---

## Selected Publications:

1.  **Santhoshi N. Krishnan**, Sunjong Ji, Ahmed M. Elhossiny, Achyutha Rao, Timothy L. Frankel, and Arvind Rao. Proximogram—a multi-omics network-based framework to capture tissue heterogeneity integrating single-cell omics and spatial profiling. Computers in Biology and Medicine, volume 182, page 109082, 2024

2.  Ashley P. Tsang\*, **Santhoshi N. Krishnan\***, Joel N. Eliason\*, Jake J. McGue, Angel Qin, Timothy L. Frankel, and Arvind Rao. Assessing the tumor immune landscape across multiple spatial scales to differentiate immunotherapy response in metastatic non-small cell lung cancer. Laboratory Investigation, volume 104, page 102148, 2024.

3.  Julienne L. Carstens, **Santhoshi Krishnan**, Arvind Rao, and et al. Spatial multiplexing and omics. Nature Reviews Methods Primers, volume 4, page 54, 2024.

4.  Omar A. Saldarriaga, Timothy G. Wanninger, Esteban Arroyave, Joseph Gosnell, **Santhoshi Krishnan**, Morgan Oneka, Daniel Bao, Daniel E. Millian, Michael L. Kueht, Akshata Moghe, and et al. Heterogeneity in intrahepatic macrophage populations and druggable target expression in patients with steatotic liver disease-related fibrosis. JHEP Reports, volume 6, page 100958, Jan 2024.

5.  Brian D. Griffith, Jenny Lazarus, Jake McGue, **Santhoshi Krishnan**, Michael I. D'Angelica, Jinru Shia, Irina Dobrosotskaya, Jaiqi Shi, Jacob Edwards, Arvind Rao, and et al. Unique characteristics of the tumor immune microenvironment in young patients with metastatic colorectal cancer. Frontiers in Immunology, volume 14, Dec 2023

6.  Alejandro Francisco-Cruz, Pedro Rocha, Alexandre Reuben, **Santhoshi Krishnan**, Priyam Das, Runzhe Chen, Kelly Quek, Jun Li, Edwin R. Parra, Luisa M. Solis, and et al. Analysis of immune intratumor heterogeneity highlights immunoregulatory and coinhibitory lymphocytes as hallmarks\
    of recurrence in stage i non--small cell lung cancer. Modern Pathology, volume 36, page 100028, 2023

7.  **Santhoshi N Krishnan** , Souptik Barua, Timothy L Frankel, and Arvind Rao. Towards the characterization of the tumor microenvironment through dictionary learning-based interpretable classification of multiplexed immunofluorescence images. Physics in Medicine & Biology, volume 68, page 014002, 2022.

8.  **Santhoshi Krishnan\*** , Shariq Mohammed\*, Timothy Frankel, and Arvind Rao. Gawrdenmap: A quantitative framework to study the local variation in cell-cell interactions in pancreatic disease subtypes. Scientific Reports, 2022.

9.  Angel Qin, Fatima Lima, Samantha Bell, Gregory P. Kalemkerian, Bryan J. Schneider, Nithya Ramnath, Madelyn Lew, **Santhoshi Krishnan**, Shariq Mohammed, Arvind Rao, and et al. Cellular engagement and interaction in the tumor microenvironment predict non-response to pd-1/pd-l1 inhibitors in metastatic non-small cell lung cancer. Scientific Reports, volume 12, 2022.

10. Mayank Baranwal, **Santhoshi Krishnan**, Morgan Oneka, Timothy Frankel, and Arvind Rao. Cgat: Cell graph attention network for grading of pancreatic disease histology images. Frontiers in Immunology, volume 12, 2021.

11. Omar A. Saldarriaga, Benjamin Freiberg, **Santhoshi Krishnan**, Arvind Rao, Jared Burks, Adam L. Booth, Bradley Dye, Netanya Utay, Monique Ferguson, Abdellah Akil, and et al. Multispectral imaging enables characterization of intrahepatic macrophages in patients with chronic liver disease. Hepatology Communications, volume 4, page 708--723, 2020.

12. Olivia D. Lara, **Santhoshi Krishnan**, Zhihui Wang, Sara Corvigno, Yanping Zhong, Yasmin Lyons, Robert Dood, Wei Hu, Lisha Qi, Jinsong Liu, and et al. Tumor core biopsies adequately represent immune microenvironment of high-grade serous carcinoma. Scientific Reports, volume 9, 2019.

13. C.R. Parvathy\*, Meghna Hukeri\*, **Santhoshi Krishnan\***, Anburajan Mariamicheal, and Oinam Robita Chanu. Study of changes in surface temperature of facial region due to mobile phone radiation. 2015 International Conference on Innovations in Information, Embedded and Communication Systems (ICIIECS), 2015.

    \*equal contribution

## Oral Presentations:

1.  Where do we start looking?Analysis of Spatial Imaging Data . Presented virtually in the Biocompare Webinar Series "Overcoming Technical Challenges in Spatial Biology" on 21st November, 2024.

2.  Methods for the characterization of tumor heterogeneity with a spatial context. Presented at the 6th Annual Symposium-Cancer Research: Basic Science to Bioinformatics at College Station, TX, on 29th September, 2023.

3.  Analysis platforms to quantify tumor-immune interactions through multiplexed spatial profiling technologies. Presented at the 20th Discovery on Target(DOT) Conference at Boston, MA, on 25th September, 2023.

4.  Location matters : Methods for the characterization of the tumor microenvironment with a spatial context. Presented at the 32nd Great Lakes International Imaging and Flow Cytometry Association at Madison, WI, on 9th-10th September, 2023.

## Poster Presentations:

1.  Santhoshi Krishnan, Sunjong Ji, Ahmed M. Elhossiny, Achyutha Rao, Timothy L. Frankel, and Arvind Rao. The Proximogram: A network-based multi-omics approach to capture tissue differences with single-cell and spatial profiling. In DATA Fall 2024 Industry Advisory Board Meeting, 25 September 2024.

2.  Santhoshi Krishnan, Shariq Mohhammed, Timothy L. Frankel, and Arvind Rao. Gawrdenmap: A spatially-informed framework to quantify heterogeneity in inter-cellular interactions. In 30th Conference for Intelligent Systems for Molecular Biology(ISMB),10-14 July, 2022.

3.  Santhoshi Krishnan, Morgan Oneka, Emily Belille, Katie Zarins, Johnathan McHugh, Jeremy M.G. Taylor, Maureen Sartor, Laura Rozek, and Arvind Rao. A quantitative framework to characterize tumor immune cell spatial interactions in head and neck squamous cell carcinoma. In Keystone eSymposia on Advances in Cancer Immunotherapy-2020, 17-19 August 2020. Keystone Symposia, 2020.

4.  Laura Rozek, Santhoshi Krishnan, Katie Zarins, Jonathan McHugh, Jeremy M.G. Taylor, Emily Belille, Steven B Chinn, Gregory T Wolf, Arvind Rao, and Maureen Sartor. Synthesizing tumor infiltrating lymphocyte patterns with genomic measurements for head and neck cancer survival. In 2020 Precision Health Virtual Symposium,23-24 September, 2020.
